---
- name: Test AWX -> OpenStack Instance Create
  hosts: localhost
    
  tasks:
  - name: New SNS instance, attach to network
    os_server:
       state: present
       name: EVA_VM_AWX
       image: EVA_VPAYG_OpenStack
       key_name: vm
       timeout: 200
       flavor: m1.medium
       auto_ip: yes
       nics:
        - net-name: private
       security_groups: default
  - name: Floating IP for the SNS firewall
    os_floating_ip:
        state: present
        server: EVA_VM_AWX
        network: public
        nat_destination: private
        reuse: yes
        wait: true
        timeout: 40
    register: output
  - name: Debug floating IP output (to the variable)
    set_fact: 
        output: "{{ output.floating_ip.floating_ip_address }}"
  - name: SNS EVA Floating IP
    debug:
        msg: "{{ output }}"
  - name: Passing the EVA FW IP to the workflow
    set_stats:
       data:
        IP_FIREWALL: "{{ output }}"
        
