---
- hosts: localhost
  connection: local
  vars:
    appliance:
      host: 10.0.0.147
      user: admin
      password: telewiz6
      sslverifyhost: False
    ntp:
      host: fr.pool.ntp.org
      ip: 178.33.214.167

  tasks:
    - name: Set up NTP service
      sns_command:
        appliance: "{{ appliance }}"
        script: |
          CONFIG OBJECT HOST NEW name="{{ ntp.host }}"" ip="{{ ntp.ip }}" resolve=dynamic update=1
          CONFIG OBJECT ACTIVATE
          CONFIG NTP SERVER ADD name={{ ntp.host }}
          CONFIG NTP ACTIVATE
