---
- hosts: "{{ IP_FIREWALL }}"
  remote_user: admin
  vars:
    ansible_become_pass: telewiz6
  tasks:
  - name: HTTP request using EVA curltool
    command: curltool -r POST -u http://10.10.10.137:5555 -p post_param1=10.0.0.142
