---
- hosts: localhost
  connection: local
  vars:
    appliance:
      host: "{{ IP_FIREWALL }}"
      user: admin
      password: telewiz6
      sslverifyhost: False
    endpoint:
      ip: 10.10.10.137

  tasks:
    - name: Sending HTTP POST to the endpoint with params
      sns_command:
        appliance: "{{ appliance }}"
        script: |
          curltool -r POST -u http://10.10.10.137:5555 -p post_param1="{{ IP_FIREWALL }}"
